# Production Environment Configuration

# Service configuration
service_name: "bitcoin-ingestor"
environment: "prod"
mode: "sbe"  # Production uses SBE streaming only

# Binance configuration
binance:
  rest_base_url: "https://data-api.binance.vision"
  sbe_ws_url: "wss://stream-sbe.binance.com/ws"
  symbols: ["BTCUSDT"]
  rate_limit_requests_per_minute: 1200
  request_timeout_seconds: 30
  api_key: ${BINANCE_API_KEY}
  sbe_schema_version: "1:0"

# AWS configuration
aws:
  region: "us-east-1"
  # AWS credentials (use IAM roles in production, environment variables for local testing)
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  # Kinesis Data Streams
  kinesis_trade_stream: "market-sbe-trade"
  kinesis_bba_stream: "market-sbe-bestbidask"
  kinesis_depth_stream: "market-sbe-depth"
  kinesis_batch_size: 500
  kinesis_flush_interval_seconds: 1
  # S3
  s3_bucket: "bitcoin-data-lake"
  s3_bronze_prefix: "bronze"

# Retry configuration
retry:
  max_attempts: 5
  initial_backoff_seconds: 1.0
  max_backoff_seconds: 60.0
  backoff_multiplier: 2.0
  jitter: true

# Health check configuration
health:
  port: 8080
  host: "0.0.0.0"
  endpoint: "/health"

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  output: "stdout"

# Metrics configuration
metrics:
  enable_prometheus: false  # Use CloudWatch in production
  prometheus_port: 8081
  enable_cloudwatch: true
  metrics_namespace: "BitcoinPipeline/Ingestor"

# Schema paths
schema_base_path: "../../schemas/avro"